export const ImagePath = {
  landing: require('../assets/image/landing.jpg'),
  registration1: require('../assets/image/registration1.jpg'),
  registration2: require('../assets/image/registration2.jpg'),
  registration3: require('../assets/image/registration3.jpg'),
  logo: require('../assets/image/logo.png'),
  noInternet: require('../assets/image/noInternet.jpg'),
  welcome: require('../assets/image/welcome.jpg'),
  login: require('../assets/image/login.jpg'),
  user: require('../assets/image/user.png'),
  subscription: require('../assets/image/one.png'),
  breakfast: require('../assets/image/two.png'),
  Lunch: require('../assets/image/three.png'),
  dinner: require('../assets/image/four.png'),
  TopOffer: require('../assets/image/fice.png'),
  f1: require('../assets/image/f1.png'),
  f2: require('../assets/image/f2.png'),
  f3: require('../assets/image/f3.png'),
  f4: require('../assets/image/f4.png'),
  f5: require('../assets/image/f5.png'),
  f6: require('../assets/image/f6.png'),
  f7: require('../assets/image/f7.png'),
  f8: require('../assets/image/f8.png'),
  f9: require('../assets/image/f9.png'),
};
